### ISSUE TITLE
Missing auth on the plugin 

### ISSUE THREAD

**Issue by Spriingy** [XeroxDev/Loupedeck-plugin-NanoleafControl#2]
Into the plugin the Auth button missing, i can't control my light

**Comment by XeroxDev** [comment]
Hey! I've looked into it but can't replicate this issue. But I'll try to look even deeper into it due to the amount of reports.

**Comment by chinyau** [comment]
Similar, no auth button... thanks for looking into it.

**Comment by brennanmuir** [comment]
This is missing for me as well

<img width="258" alt="image" src="https://user-images.githubusercontent.com/18177606/216214743-fe7200ea-35a7-4134-8b5f-557ad74bcfa6.png">

**Comment by XeroxDev** [comment]
@brennanmuir it'll be fixed in the next version (code is already done and online). Sadly I didn't had time yet to release it in the store.

**Comment by SamBukka** [comment]
hi XeroxDev, 
first  i will thank you for your hard work, but we need the update for the missing auth button.
Thx a lot, and greetings from germany

**Comment by XeroxDev** [comment]
Good news. The update will be released this weekend.

**Comment by SamBukka** [comment]
Great news 👍
